### ISSUE TITLE
There is no way to force color output

### ISSUE THREAD

**Issue by maciejmatczak** [joknarf/pgtree#7]
Hi there,

Usually CLI utils supporting coloring have a way to enforce colored output apart from "no color" and "auto" (tty recognition).

This is helpful when used in `watch -n1`, etc. `pgtree` currently prints non-colored version, it seems.

Great little utility btw!

**Comment by joknarf** [comment]
Hi Maciej,
I totally agree, I also found annoying about this.
I made the release 1.0.15 with option -C always/never/auto (default auto).
But I found the `watch` command with --color option (-c) is only working with 16 colors ansi codes on most versions (using 256 colors in pgtree)
Only version working found is 3.3.17 (default in CentOS 9).
See in changelog : 
```
Release 3.3.17
...
 * watch: Support more colors                             merge #106,#109
```
I will release soon a new version with 16 colors ANSI codes, to make pgtree more compatible with old watch command
So currently only working with watch 3.3.17:
`watch -c pgtree -C always -c gnome-session`
<img width="769" alt="Capture d’écran 2022-07-12 à 23 18 57" src="https://user-images.githubusercontent.com/10117818/178598332-020516fb-f4f0-4cd8-b7c8-cb30febcc608.png">

**Comment by joknarf** [comment]
Ok, release [1.0.16](https://github.com/joknarf/pgtree/releases/tag/v1.0.16) is now using 16 colors ANSI codes, and will be more compatible with `watch` command.
The -C option now accepts y/yes/always/n/no/never.
Added the -w option to prevent text wrapping on tty ouput (-w n or -w no)
